policy('Policy (b)', 'File Management', [
  user(u1),
  user(u2),
  user_attribute('Alice'),
  user_attribute('Bob'),
  user_attribute('Users'),
  object(o2),
  object(o3),
  object(o4),
  object_attribute('Proposals'),
  object_attribute('Reports'),
  object_attribute('Bob Home'),
  policy_class('File Management'),
  connector('PM'),
  assign(u1,'Alice'),
  assign(u2,'Bob'),
  assign('Alice','Users'),
  assign('Bob','Users'),
  assign(o2,'Proposals'),
  assign(o3,'Reports'),
  assign(o4,'Reports'),
  assign('Proposals','Bob Home'),
  assign('Reports','Bob Home'),
  assign('Users','File Management'),
  assign('Bob Home','File Management'),
  assign('File Management','PM'),
  associate('Bob',[r,w],'Bob Home'),
  associate('Alice',[r,w],o2)
]).
